<a href="https://colab.research.google.com/github/CKBoppudi/CKBoppudi/blob/main/Text_representation_feature_enginerring_using_bag_of_words.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
 import numpy as np
 import pandas as pd 

In [12]:
data = pd.read_csv(r"/content/spam.csv")

In [13]:
data

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [14]:
data["Category"].value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [20]:
data["spam"] = data["Category"].apply(lambda x : 1 if x == "spam" else 0)

In [21]:
def get_spam_number(x):
  if x == "spam":
    return 1
  else:
    return 0

In [22]:
data["spam"] = data["Category"].apply(get_spam_number)

In [23]:
data.head(10)

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0
5     spam  FreeMsg Hey there darling it's been 3 week's n...     1
6      ham  Even my brother is not like to speak with me. ...     0
7      ham  As per your request 'Melle Melle (Oru Minnamin...     0
8     spam  WINNER!! As a valued network customer you have...     1
9     spam  Had your mobile 11 months or more? U R entitle...     1

In [26]:
from sklearn.model_selection import train_test_split

x_train , x_test , y_train , y_test = train_test_split(data["Message"] , data["spam"] , test_size = 0.2)

In [28]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(4457,)
(1115,)
(4457,)
(1115,)


In [35]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

x_train_cv = v.fit_transform(x_train)

x_train_cv

<4457x7751 sparse matrix of type '<class 'numpy.int64'>'
	with 59187 stored elements in Compressed Sparse Row format>

In [41]:
x_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [42]:
 x_train_cv.shape

(4457, 7751)

In [78]:
v.get_feature_names_out()[7465]

'well'

In [ ]:
v.vocabulary_

In [63]:
x_train_np = x_train_cv.toarray()

x_train_np[:4][0]

array([0, 0, 0, ..., 0, 0, 0])

In [75]:
np.where(x_train_np[1] != 0)


(array([ 944, 1083, 2413, 2876, 3359, 3605, 7234, 7465]),)

In [76]:
 x_train[:4][2601]

'As usual..iam fine, happy &amp; doing well..:)'

In [72]:
x_train_np[0][3382]

1

# Building machine learning model (MultinomialNB)

In [82]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()

model.fit(x_train_cv , y_train)

MultinomialNB()

In [83]:
x_test_cv = v.transform(x_test)

In [92]:
from sklearn.metrics import classification_report

y_prediction = model.predict(x_test_cv)

print(classification_report(y_test , y_prediction))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99       948
           1       0.98      0.90      0.94       167

    accuracy                           0.98      1115
   macro avg       0.98      0.95      0.97      1115
weighted avg       0.98      0.98      0.98      1115



In [111]:
emails = ["Hello Chandrakanth! Hope you are doing great.",
          "Hey you have won a jackpot of $ 75,000." ,
          "Hey CK. How about joining me for cricket this weekend." ,
          "Amresh,Thanks for the support and the pricing, the demo went well."]

In [112]:
emails_cv = v.transform(emails)

In [113]:
model.predict(emails_cv)

array([0, 1, 0, 0])

Doing all this using a simpler method of sklearn pipeline.

In [120]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ("vectorizer" , CountVectorizer()) , 
    ("nb" , MultinomialNB())
])

In [121]:
clf.fit(x_train , y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [124]:
y_prediction = clf.predict(x_test)

print(classification_report(y_test , y_prediction))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99       948
           1       0.98      0.90      0.94       167

    accuracy                           0.98      1115
   macro avg       0.98      0.95      0.97      1115
weighted avg       0.98      0.98      0.98      1115



In [124]:
emails = ["Hello Chandrakanth! Hope you are doing great.",
          "Hey you have won a jackpot of $ 75,000." ,
          "Hey CK. How about joining me for cricket this weekend." ,
          "Amresh,Thanks for the support and the pricing, the demo went well."]

In [125]:
clf.predict(emails)

array([0, 1, 0, 0])